import { LinearGauge } from '../../vendor/gauge.min.js';

const linearGauge1 = new LinearGauge({
  renderTo: 'linearGauge1',
  width: 125,
  height: 260,
  //title: 'Уровень, л/с',
  units: "Уровень, л/с",
  value: '100',
  minValue: '0',
  maxValue: '250',
  valueBox: true,
  /* borders: 0,
  borderRadius: 0, */
  barWidth: 13,
  barBeginCircle: false,
  colorBarProgress: "rgba(255,255,255,.75)",
  colorBar: "rgba(255,255,255,.25)",
  strokeTicks: true,
  majorTicks: ['0', '50', '100', '150', '200', '250'],
  minorTicks: '5',
  highlights: [
      { "from": 0, "to": 25, "color": "red" },
      { "from": 200, "to": 250, "color": "red" }
  ],
  colorPlate: "transparent",
  colorMajorTicks: "#f5f5f5",
  colorMinorTicks: "#ddd",
  colorTitle: "#fff",
  colorUnits: "#fff",
  colorNumbers: "#fff",
  borders: false,
  tickSide: 'right',
  numberSide: 'right',
  needleSide: 'left',
  animationRule: 'linear',
  animatedValue: true,
  animationDuration: 1000,
  animation: true,
  // BoxBorderRadius: 0,
  // textShadow: 'false',
  fontNumbersSize: 26,
  fontTitleSize: 26,
  fontUnitsSize: 26,
  fontValueSize: 36,
  fontValue: "TimeBomb",
  fontNumbers: "TimeBomb",
  glow : true,
  colorValueBoxRect: "transparent",
  colorValueBoxRectEnd: "transparent",
  colorValueBoxBackground: "transparent",
  colorValueText: "#fff",
}).draw();

const linearGauge2 = new LinearGauge({
  renderTo: 'linearGauge2',
  width: 125,
  height: 260,
  //title: 'Уровень, л/с',
  units: "Уровень, л/с",
  value: '100',
  minValue: '0',
  maxValue: '250',
  valueBox: true,
  /* borders: 0,
  borderRadius: 0, */
  barWidth: 13,
  barBeginCircle: false,
  colorBarProgress: "rgba(255,255,255,.75)",
  colorBar: "rgba(255,255,255,.25)",
  strokeTicks: true,
  majorTicks: ['0', '50', '100', '150', '200', '250'],
  minorTicks: '5',
  highlights: [
      { "from": 0, "to": 25, "color": "red" },
      { "from": 200, "to": 250, "color": "red" }
  ],
  colorPlate: "transparent",
  colorMajorTicks: "#f5f5f5",
  colorMinorTicks: "#ddd",
  colorTitle: "#fff",
  colorUnits: "#fff",
  colorNumbers: "#fff",
  borders: false,
  tickSide: 'right',
  numberSide: 'right',
  needleSide: 'left',
  animationRule: 'linear',
  animatedValue: true,
  animationDuration: 1000,
  animation: true,
  // BoxBorderRadius: 0,
  // textShadow: 'false',
  fontNumbersSize: 26,
  fontTitleSize: 26,
  fontUnitsSize: 26,
  fontValueSize: 36,
  fontValue: "TimeBomb",
  fontNumbers: "TimeBomb",
  glow : true,
  colorValueBoxRect: "transparent",
  colorValueBoxRectEnd: "transparent",
  colorValueBoxBackground: "transparent",
  colorValueText: "#fff",
}).draw();

const linearGauge3 = new LinearGauge({
  renderTo: 'linearGauge3',
  width: 125,
  height: 260,
  //title: 'Уровень, л/с',
  units: "Уровень, л/с",
  value: '100',
  minValue: '0',
  maxValue: '250',
  valueBox: true,
  /* borders: 0,
  borderRadius: 0, */
  barWidth: 13,
  barBeginCircle: false,
  colorBarProgress: "rgba(255,255,255,.75)",
  colorBar: "rgba(255,255,255,.25)",
  strokeTicks: true,
  majorTicks: ['0', '50', '100', '150', '200', '250'],
  minorTicks: '5',
  highlights: [
      { "from": 0, "to": 25, "color": "red" },
      { "from": 200, "to": 250, "color": "red" }
  ],
  colorPlate: "transparent",
  colorMajorTicks: "#f5f5f5",
  colorMinorTicks: "#ddd",
  colorTitle: "#fff",
  colorUnits: "#fff",
  colorNumbers: "#fff",
  borders: false,
  tickSide: 'right',
  numberSide: 'right',
  needleSide: 'left',
  animationRule: 'linear',
  animatedValue: true,
  animationDuration: 1000,
  animation: true,
  // BoxBorderRadius: 0,
  // textShadow: 'false',
  fontNumbersSize: 26,
  fontTitleSize: 26,
  fontUnitsSize: 26,
  fontValueSize: 36,
  fontValue: "TimeBomb",
  fontNumbers: "TimeBomb",
  glow : true,
  colorValueBoxRect: "transparent",
  colorValueBoxRectEnd: "transparent",
  colorValueBoxBackground: "transparent",
  colorValueText: "#fff",
}).draw();

const linearGauge4 = new LinearGauge({
  renderTo: 'linearGauge4',
  width: 125,
  height: 260,
  //title: 'Уровень, л/с',
  units: "Уровень, л/с",
  value: '100',
  minValue: '0',
  maxValue: '250',
  valueBox: true,
  /* borders: 0,
  borderRadius: 0, */
  barWidth: 13,
  barBeginCircle: false,
  colorBarProgress: "rgba(255,255,255,.75)",
  colorBar: "rgba(255,255,255,.25)",
  strokeTicks: true,
  majorTicks: ['0', '50', '100', '150', '200', '250'],
  minorTicks: '5',
  highlights: [
      { "from": 0, "to": 25, "color": "red" },
      { "from": 200, "to": 250, "color": "red" }
  ],
  colorPlate: "transparent",
  colorMajorTicks: "#f5f5f5",
  colorMinorTicks: "#ddd",
  colorTitle: "#fff",
  colorUnits: "#fff",
  colorNumbers: "#fff",
  borders: false,
  tickSide: 'right',
  numberSide: 'right',
  needleSide: 'left',
  animationRule: 'linear',
  animatedValue: true,
  animationDuration: 1000,
  animation: true,
  // BoxBorderRadius: 0,
  // textShadow: 'false',
  fontNumbersSize: 26,
  fontTitleSize: 26,
  fontUnitsSize: 26,
  fontValueSize: 36,
  fontValue: "TimeBomb",
  fontNumbers: "TimeBomb",
  glow : true,
  colorValueBoxRect: "transparent",
  colorValueBoxRectEnd: "transparent",
  colorValueBoxBackground: "transparent",
  colorValueText: "#fff",
}).draw();

const linearGauge5 = new LinearGauge({
  renderTo: 'linearGauge5',
  width: 125,
  height: 260,
  //title: 'Уровень, л/с',
  units: "Уровень, л/с",
  value: '100',
  minValue: '0',
  maxValue: '250',
  valueBox: true,
  /* borders: 0,
  borderRadius: 0, */
  barWidth: 13,
  barBeginCircle: false,
  colorBarProgress: "rgba(255,255,255,.75)",
  colorBar: "rgba(255,255,255,.25)",
  strokeTicks: true,
  majorTicks: ['0', '50', '100', '150', '200', '250'],
  minorTicks: '5',
  highlights: [
      { "from": 0, "to": 25, "color": "red" },
      { "from": 200, "to": 250, "color": "red" }
  ],
  colorPlate: "transparent",
  colorMajorTicks: "#f5f5f5",
  colorMinorTicks: "#ddd",
  colorTitle: "#fff",
  colorUnits: "#fff",
  colorNumbers: "#fff",
  borders: false,
  tickSide: 'right',
  numberSide: 'right',
  needleSide: 'left',
  animationRule: 'linear',
  animatedValue: true,
  animationDuration: 1000,
  animation: true,
  // BoxBorderRadius: 0,
  // textShadow: 'false',
  fontNumbersSize: 26,
  fontTitleSize: 26,
  fontUnitsSize: 26,
  fontValueSize: 36,
  fontValue: "TimeBomb",
  fontNumbers: "TimeBomb",
  glow : true,
  colorValueBoxRect: "transparent",
  colorValueBoxRectEnd: "transparent",
  colorValueBoxBackground: "transparent",
  colorValueText: "#fff",
}).draw();

const linearGauge6 = new LinearGauge({
  renderTo: 'linearGauge6',
  width: 125,
  height: 260,
  //title: 'Уровень, л/с',
  units: "Уровень, л/с",
  value: '100',
  minValue: '0',
  maxValue: '250',
  valueBox: true,
  /* borders: 0,
  borderRadius: 0, */
  barWidth: 13,
  barBeginCircle: false,
  colorBarProgress: "rgba(255,255,255,.75)",
  colorBar: "rgba(255,255,255,.25)",
  strokeTicks: true,
  majorTicks: ['0', '50', '100', '150', '200', '250'],
  minorTicks: '5',
  highlights: [
      { "from": 0, "to": 25, "color": "red" },
      { "from": 200, "to": 250, "color": "red" }
  ],
  colorPlate: "transparent",
  colorMajorTicks: "#f5f5f5",
  colorMinorTicks: "#ddd",
  colorTitle: "#fff",
  colorUnits: "#fff",
  colorNumbers: "#fff",
  borders: false,
  tickSide: 'right',
  numberSide: 'right',
  needleSide: 'left',
  animationRule: 'linear',
  animatedValue: true,
  animationDuration: 1000,
  animation: true,
  // BoxBorderRadius: 0,
  // textShadow: 'false',
  fontNumbersSize: 26,
  fontTitleSize: 26,
  fontUnitsSize: 26,
  fontValueSize: 36,
  fontValue: "TimeBomb",
  fontNumbers: "TimeBomb",
  glow : true,
  colorValueBoxRect: "transparent",
  colorValueBoxRectEnd: "transparent",
  colorValueBoxBackground: "transparent",
  colorValueText: "#fff",
}).draw();

const linearGauge7 = new LinearGauge({
  renderTo: 'linearGauge7',
  width: 125,
  height: 260,
  //title: 'Уровень, л/с',
  units: "Уровень, л/с",
  value: '100',
  minValue: '0',
  maxValue: '250',
  valueBox: true,
  /* borders: 0,
  borderRadius: 0, */
  barWidth: 13,
  barBeginCircle: false,
  colorBarProgress: "rgba(255,255,255,.75)",
  colorBar: "rgba(255,255,255,.25)",
  strokeTicks: true,
  majorTicks: ['0', '50', '100', '150', '200', '250'],
  minorTicks: '5',
  highlights: [
      { "from": 0, "to": 25, "color": "red" },
      { "from": 200, "to": 250, "color": "red" }
  ],
  colorPlate: "transparent",
  colorMajorTicks: "#f5f5f5",
  colorMinorTicks: "#ddd",
  colorTitle: "#fff",
  colorUnits: "#fff",
  colorNumbers: "#fff",
  borders: false,
  tickSide: 'right',
  numberSide: 'right',
  needleSide: 'left',
  animationRule: 'linear',
  animatedValue: true,
  animationDuration: 1000,
  animation: true,
  // BoxBorderRadius: 0,
  // textShadow: 'false',
  fontNumbersSize: 26,
  fontTitleSize: 26,
  fontUnitsSize: 26,
  fontValueSize: 36,
  fontValue: "TimeBomb",
  fontNumbers: "TimeBomb",
  glow : true,
  colorValueBoxRect: "transparent",
  colorValueBoxRectEnd: "transparent",
  colorValueBoxBackground: "transparent",
  colorValueText: "#fff",
}).draw();

const linearGauge8 = new LinearGauge({
  renderTo: 'linearGauge8',
  width: 125,
  height: 260,
  //title: 'Уровень, л/с',
  units: "Уровень, л/с",
  value: '100',
  minValue: '0',
  maxValue: '250',
  valueBox: true,
  /* borders: 0,
  borderRadius: 0, */
  barWidth: 13,
  barBeginCircle: false,
  colorBarProgress: "rgba(255,255,255,.75)",
  colorBar: "rgba(255,255,255,.25)",
  strokeTicks: true,
  majorTicks: ['0', '50', '100', '150', '200', '250'],
  minorTicks: '2',
  highlights: [
      { "from": 0, "to": 25, "color": "red" },
      { "from": 200, "to": 250, "color": "red" }
  ],
  colorPlate: "transparent",
  colorMajorTicks: "#f5f5f5",
  colorMinorTicks: "#ddd",
  colorTitle: "#fff",
  colorUnits: "#fff",
  colorNumbers: "#fff",
  borders: false,
  tickSide: 'right',
  numberSide: 'right',
  needleSide: 'left',
  animationRule: 'linear',
  animatedValue: true,
  animationDuration: 2000,
  animation: true,
  // BoxBorderRadius: 0,
  // textShadow: 'false',
  fontNumbersSize: 26,
  fontTitleSize: 26,
  fontUnitsSize: 26,
  fontValueSize: 36,
  fontValue: "TimeBomb",
  fontNumbers: "TimeBomb",
  glow : true,
  colorValueBoxRect: "transparent",
  colorValueBoxRectEnd: "transparent",
  colorValueBoxBackground: "transparent",
  colorValueText: "#fff",
}).draw();

export { linearGauge1, linearGauge2, linearGauge3, linearGauge4, linearGauge5, linearGauge6, linearGauge7, linearGauge8 };